version: '3.8'

services:
  eteczlcatracas-php-fpm:
    build:
      context: .
      dockerfile: Dockerfile-php-fpm
    container_name: eteczlcatracas-php-fpm
    volumes:
      - ./:/var/www/html
    networks:
      - eteczlcatracas-network


  eteczlcatracas-nginx:
    image: nginx:stable-alpine
    container_name: eteczlcatracas-nginx
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - eteczlcatracas-php-fpm
    networks:
      - eteczlcatracas-network

  eteczlcatracas-mysql:
    image: mysql:8.0
    container_name: eteczlcatracas-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234 # Senha do usuário root do MySQL
      MYSQL_DATABASE: eteczlcatracas_db # Nome do banco de dados a ser criado
      MYSQL_USER: eteczlcatracas_user # Usuário do banco de dados
      MYSQL_PASSWORD: 1234 # Senha do usuário do banco de dados
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u$$MYSQL_USER", "-p$$MYSQL_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - ./eteczlcatracas-db-data:/var/lib/mysql # Volume nomeado para persistência dos dados do MySQL
      - ./my-custom.cnf:/etc/mysql/conf.d/my-custom.cnf
    networks:
      - eteczlcatracas-network
 
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8888:80'
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=eteczlcatracas-mysql
    depends_on:
      - eteczlcatracas-mysql
    networks:
      - eteczlcatracas-network

# Definição de volumes nomeados para persistência de dados
#volumes:
#  eteczlcatracas-db-data: # Volume para os dados do MySQL

# Definição de redes personalizadas para comunicação entre os serviços
networks:
  eteczlcatracas-network:
    driver: bridge # Tipo de rede (bridge é o padrão e mais comum)
